dataset_loader: 'OxfordEmbeddingPad'
data_dir: 'oxford_compressed/'
train_queries: 'oxford_compressed/training_queries_baseline.pickle'
test_queries: 'oxford_compressed/test_queries_baseline.pickle'
num_positives: 2
num_negatives: 18
batch_size: 16
num_worker: 6
get_negatives: False
